version: "2"
services:
  quickapp_db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: quickapp_db 
      environment:
        - SA_PASSWORD=devopsify@123
        - ACCEPT_EULA="Y"
  quickapp_webapi:
      image: huyntt/demo-quickapp-api
      depends_on:
          - quickapp_db
      container_name: quickapp_webapi
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=testing
        - ConnectionStrings:DefaultConnection=Server=quickapp_db,1433;Database=QuickApp;User Id=sa;Password=devopsify@123;
      ports: 
        - "9081:80"
  quickapp_webapp:
      image: huyntt/demo-quickapp-web
      container_name: quickapp_webapp
      depends_on:
        - quickapp_webapi
      ports: 
        - "9080:80"