version: "2"
services:
  db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: quickappdb 
      environment:
        - SA_PASSWORD=${SA_PASSWORD}
        - ACCEPT_EULA=${ACCEPT_EULA}
  be:
      image: huyntt/demo-quickapp-api
      depends_on:
          - db
      container_name: app
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ${ConnectionStrings}
        - ASPNETCORE_URLS=${ASPNETCORE_URLS}
        #- ASPNETCORE_HTTPS_PORT=8001 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel_Password}
        - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel_Path}
      ports: 
        - "9081:${app_port}"
  fe:
      image: "localhost:8085/web-app_${ASPNETCORE_ENVIRONMENT}:IMAGES_TAG"
      container_name: angular_app
      depends_on:
        - be
      ports: 
        - "9080:80"  
        - "9443:443"